### ISSUE TITLE
Socket cliente

### ISSUE THREAD

**Issue by SergioFernandez55** [ECCIUCRLQ/sensores-equipo-404#1]
Socket que envie datos cada segundo basado en los datos del sensor. Hay que manejar el número de secuencia.

**Comment by JoseAndresMejiasRojas** [comment]
La generación de un número de sequencia ya se implementó por el issue de Struct y serialización, ya que tenía que ver con el paquete en sí.

**Comment by JoseAndresMejiasRojas** [comment]
Pendiente para mañana implementar la captura de datos de ambos sensores y poder enviarlos.

**Comment by JoseAndresMejiasRojas** [comment]
Probado con todos los equipos.
