### ISSUE TITLE
Escribir en páginas

### ISSUE THREAD

**Issue by jarayamurillo** [ECCIUCRLQ/sensores-equipo-404#29]

**Comment by JoseAndresMejiasRojas** [comment]
Hay progreso: https://github.com/ECCIUCRLQ/sensores-equipo-404/commit/ded9548a16ca3e16eac9efc8d2b16f8b348e46ed permite que se escriba páginas en la memoria principal.  Faltan las páginas que estén en memoria secundaria.

**Comment by JoseAndresMejiasRojas** [comment]
Listo con primary y secundaria https://github.com/ECCIUCRLQ/sensores-equipo-404/commit/3b10740fff5991063ff38029767b18afd9987114
