### ISSUE TITLE
Swapping de páginas

### ISSUE THREAD

**Issue by jarayamurillo** [ECCIUCRLQ/sensores-equipo-404#32]

**Comment by JoseAndresMejiasRojas** [comment]
En caso de que haya más de 13 sensores.

**Comment by JoseAndresMejiasRojas** [comment]
Este issue es ambiguo, ya que el swapping también significa que, cuando una página se llene, mandarla a memoria secundaria.

El caso de que haya más de 13 sensores hay que discutirlo.

**Comment by JoseAndresMejiasRojas** [comment]
Listo con https://github.com/ECCIUCRLQ/sensores-equipo-404/commit/3b10740fff5991063ff38029767b18afd9987114

**Comment by JoseAndresMejiasRojas** [comment]
Listo con https://github.com/ECCIUCRLQ/sensores-equipo-404/commit/2af9960274e82a465fdfaf5f3ee69f16e2399fe8
